---

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: test
  labels:
    app: ingress-nginx

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: test

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: test

